name: Build Project using GCC8

on:
  workflow_dispatch: # To authorize manual run
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Install GCC and G++
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-8 g++-8

      - name: Set compiler paths
        run: |
          export CC=/usr/bin/gcc-8
          export CXX=/usr/bin/g++-8

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=../toolchain/gcc-8-linux.cmake ..
          make
