name: Build C++ project with Visual Studio

on:
  workflow_dispatch: # To authorize manual run
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up MSVC
        uses: microsoft/setup-msbuild@v1

      - name: Set up CMake
        uses: microsoft/setup-cmake@v1
        with:
          cmakeVersion: '3.26.x'  # Specify the desired CMake version

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          bootstrap-vcpkg.bat
          vcpkg integrate install

      - name: Determine toolchain directory
        id: toolchain
        run: |
          vcpkg install <package_name> --dry-run
          echo "::set-output name=toolchain::$(vcpkg print-toolchain-dir)"
