name: Windows Build using MS Visual Studio

on:
  workflow_dispatch: # To authorize manual run
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up MSVC
        uses: microsoft/setup-msbuild@v1

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          bootstrap-vcpkg.bat
          vcpkg integrate install
          OUTPUT=$(./vcpkg integrate install)
          TOOLCHAIN_PATH=$(echo "$OUTPUT" | grep -oP 'CMAKE_TOOLCHAIN_FILE=\K.*')
          echo "::set-output name=toolchain_path::$TOOLCHAIN_PATH"
          cd ..

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DTOOLCHAIN_FILE="vcpkg.cmake" -DCMAKE_TOOLCHAIN_FILE=${{ steps.vcpkg.outputs.toolchain_path }} ..
          make