name: Linux Build using GCC 8

on:
  workflow_dispatch: # To authorize manual run
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 8
          platform: x64

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: prepare
        run:  |
          sudo apt-get update -y
          sudo apt-get install -y libpcsclite-dev

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=../toolchain/clang-linux.cmake ..
          make
