name: Build C++ project with Visual Studio

on:
  workflow_dispatch: # To authorize manual run
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up MSVC
        uses: microsoft/setup-msbuild@v1

      - name: Set up CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: '3.26.3'  # Specify the desired CMake version

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          bootstrap-vcpkg.bat
          vcpkg integrate install

      - name: Get vcpkg toolchain directory
        id: vcpkg
        run: echo "TOOLCHAIN=$(vcpkg print-toolchain-dir)" >> $GITHUB_ENV

      - name: Echo the value of TOOLCHAIN
        run: echo ${{ env.TOOLCHAIN }}
